/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9FVVNkfgpqE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"

export function Discussion() {
  return (
    (<div
      className="grid min-h-screen w-full grid-cols-[300px_1fr] bg-background text-foreground">
      <div className="border-r bg-muted/40 p-4 overflow-auto">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-xl font-semibold">Discussions</h2>
          <Button size="sm" variant="outline">
            <PlusIcon className="h-4 w-4" />
            New Topic
          </Button>
        </div>
        <div className="grid gap-4">
          <Link
            href="#"
            className="group flex items-center justify-between rounded-md bg-muted p-3 transition-colors hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            <div className="flex items-center gap-3">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <MessageCircleIcon className="h-5 w-5" />
              </div>
              <div>
                <div className="font-medium">Responsive Design Best Practices</div>
                <div className="text-xs text-muted-foreground">12 Replies • Last activity 2 hours ago</div>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="h-4 w-4 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">24</span>
            </div>
          </Link>
          <Link
            href="#"
            className="group flex items-center justify-between rounded-md bg-muted p-3 transition-colors hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            <div className="flex items-center gap-3">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <MessageCircleIcon className="h-5 w-5" />
              </div>
              <div>
                <div className="font-medium">Accessibility in Web Development</div>
                <div className="text-xs text-muted-foreground">8 Replies • Last activity 1 day ago</div>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="h-4 w-4 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">18</span>
            </div>
          </Link>
          <Link
            href="#"
            className="group flex items-center justify-between rounded-md bg-muted p-3 transition-colors hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            <div className="flex items-center gap-3">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <MessageCircleIcon className="h-5 w-5" />
              </div>
              <div>
                <div className="font-medium">Optimizing React Performance</div>
                <div className="text-xs text-muted-foreground">16 Replies • Last activity 3 days ago</div>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="h-4 w-4 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">32</span>
            </div>
          </Link>
          <Link
            href="#"
            className="group flex items-center justify-between rounded-md bg-muted p-3 transition-colors hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            <div className="flex items-center gap-3">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <MessageCircleIcon className="h-5 w-5" />
              </div>
              <div>
                <div className="font-medium">Mastering CSS Grid Layout</div>
                <div className="text-xs text-muted-foreground">22 Replies • Last activity 1 week ago</div>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="h-4 w-4 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">41</span>
            </div>
          </Link>
          <Link
            href="#"
            className="group flex items-center justify-between rounded-md bg-muted p-3 transition-colors hover:bg-accent hover:text-accent-foreground"
            prefetch={false}>
            <div className="flex items-center gap-3">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <MessageCircleIcon className="h-5 w-5" />
              </div>
              <div>
                <div className="font-medium">Building a Serverless Application</div>
                <div className="text-xs text-muted-foreground">9 Replies • Last activity 2 weeks ago</div>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="h-4 w-4 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">27</span>
            </div>
          </Link>
        </div>
      </div>
      <div className="flex flex-col">
        <header
          className="sticky top-0 z-10 flex h-14 items-center gap-4 border-b bg-background px-4 shadow-sm sm:h-16">
          <div className="flex-1">
            <h1 className="text-lg font-semibold">Responsive Design Best Practices</h1>
          </div>
          <div className="flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm">
                  <FilterIcon className="h-4 w-4" />
                  <span>Filter</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Filter by:</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuCheckboxItem>Newest</DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>Oldest</DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>Most Replies</DropdownMenuCheckboxItem>
                <DropdownMenuCheckboxItem>Most Likes</DropdownMenuCheckboxItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search discussions..."
                className="h-8 w-40 rounded-md border border-input bg-background pl-8 text-sm focus:outline-none focus:ring-1 focus:ring-primary sm:w-56" />
            </div>
          </div>
        </header>
        <div className="flex-1 overflow-auto p-4">
          <div className="grid gap-6">
            <div className="grid gap-3 animate-fade-in">
              <div className="flex items-center gap-3">
                <Avatar className="h-8 w-8 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>AC</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Olivia Davis</div>
                  <div className="text-xs text-muted-foreground">2 hours ago</div>
                </div>
              </div>
              <div>
                <p>
                  Responsive design is crucial for creating websites and applications that work seamlessly across a wide
                  range of devices. Some key best practices include:
                </p>
                <ul className="mt-2 list-disc space-y-2 pl-5 text-sm">
                  <li>
                    Use a mobile-first approach, designing for small screens first and then progressively enhancing for
                    larger displays. 📱💻
                  </li>
                  <li>
                    Implement a flexible grid system, such as CSS Grid or Flexbox, to create a responsive layout. 🧱🔍
                  </li>
                  <li>Optimize images, fonts, and other assets for faster loading times on mobile devices. ⚡️📲</li>
                  <li>
                    Test your designs on a variety of devices and screen sizes to ensure a consistent user experience.
                    🔍📱💻
                  </li>
                </ul>
              </div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <ThumbsUpIcon className="h-4 w-4" />
                  <span className="sr-only">Like</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <MessageCircleIcon className="h-4 w-4" />
                  <span className="sr-only">Reply</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <ShareIcon className="h-4 w-4" />
                  <span className="sr-only">Share</span>
                </Button>
              </div>
            </div>
            <div className="grid gap-3 animate-fade-in">
              <div className="flex items-center gap-3">
                <Avatar className="h-8 w-8 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">John Doe</div>
                  <div className="text-xs text-muted-foreground">1 hour ago</div>
                </div>
              </div>
              <div>
                <p>
                  Great tips! I'd also recommend using responsive typography to ensure text remains legible on small
                  screens. Adjusting font sizes, line heights, and letter spacing based on the viewport size can make a
                  big difference. 🔍📏
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <ThumbsUpIcon className="h-4 w-4" />
                  <span className="sr-only">Like</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <MessageCircleIcon className="h-4 w-4" />
                  <span className="sr-only">Reply</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <ShareIcon className="h-4 w-4" />
                  <span className="sr-only">Share</span>
                </Button>
              </div>
            </div>
            <div className="grid gap-3 animate-fade-in">
              <div className="flex items-center gap-3">
                <Avatar className="h-8 w-8 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>SA</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Sarah Anderson</div>
                  <div className="text-xs text-muted-foreground">2 hours ago</div>
                </div>
              </div>
              <div>
                <p>
                  Agreed, responsive typography is a must-have for any modern website or app. I'd also suggest using CSS
                  variables to define your font sizes and spacing, making it easier to adjust them across breakpoints.
                  🎨💻
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <ThumbsUpIcon className="h-4 w-4" />
                  <span className="sr-only">Like</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <MessageCircleIcon className="h-4 w-4" />
                  <span className="sr-only">Reply</span>
                </Button>
                <Button size="icon" variant="ghost">
                  <ShareIcon className="h-4 w-4" />
                  <span className="sr-only">Share</span>
                </Button>
              </div>
            </div>
          </div>
        </div>
        <div
          className="sticky bottom-0 z-10 border-t bg-background px-4 py-3 shadow-sm">
          <div className="relative">
            <Textarea
              placeholder="Write a reply..."
              className="h-10 w-full resize-none rounded-md border border-input bg-background pr-12 text-sm focus:outline-none focus:ring-1 focus:ring-primary" />
            <Button type="submit" size="icon" className="absolute right-2 top-2">
              <SendIcon className="h-4 w-4" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}

function FilterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function ShareIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>)
  );
}


function ThumbsUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 10v12" />
      <path
        d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>)
  );
}
