/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FWUkELynQ2p
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"

export function EducationPage() {
  return (
    (<div className="flex min-h-screen flex-col">
      <header className="bg-muted/40 py-6 px-4 md:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link
            href="#"
            className="flex items-center gap-2 animate-pulse"
            prefetch={false}>
            <MountainIcon className="h-6 w-6 text-primary" />
            <span className="text-lg font-semibold text-primary">Civic Education 🏫</span>
          </Link>
          <div className="hidden items-center gap-4 md:flex">
            <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuLink
                    href="#"
                    className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50">
                    Overview
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink
                    href="/education"
                    className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50">
                    Modules
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink
                    href="/videos"
                    className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50">
                    Videos
                  </NavigationMenuLink>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
            <div className="relative flex-1">
              <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search... 🔍"
                className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[336px] shadow-md hover:shadow-lg transition-shadow" />
            </div>
          </div>
          <Button variant="outline" size="icon" className="md:hidden animate-bounce">
            <MenuIcon className="h-6 w-6 text-primary" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="relative h-[400px] w-full overflow-hidden">
          <img src="/placeholder.svg" alt="Hero" fill className="object-cover" />
          <div
            className="absolute inset-0 bg-gradient-to-b from-transparent to-muted/50" />
          <div className="absolute inset-0 flex items-center justify-center">
            <div
              className="container mx-auto space-y-4 text-center text-primary-foreground">
              <h1
                className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl animate-fadeIn">
                Civic Education 🎓
              </h1>
              <p className="max-w-[700px] text-lg md:text-xl animate-fadeIn">
                Empower your community with our comprehensive civic education program. 💪
              </p>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 animate-bounceIn"
                prefetch={false}>
                Get Started 🚀
              </Link>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container mx-auto space-y-12">
            <Tabs defaultValue="overview">
              <TabsList className="mb-6 flex w-full justify-center gap-4">
                <TabsTrigger value="overview" className="animate-fadeIn">
                  Overview
                </TabsTrigger>
                <TabsTrigger value="modules" className="animate-fadeIn">
                  Modules
                </TabsTrigger>
                <TabsTrigger value="videos" className="animate-fadeIn">
                  Videos
                </TabsTrigger>
              </TabsList>
              <TabsContent value="overview">
                <div className="space-y-6">
                  <div className="space-y-2 animate-fadeIn">
                    <h2
                      className="text-3xl font-bold tracking-tighter sm:text-4xl bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                      Civic Education Overview 🌍
                    </h2>
                    <p className="text-muted-foreground md:text-lg">
                      Our civic education program is designed to empower individuals with the knowledge and skills
                      necessary to become active and engaged citizens. Through a comprehensive curriculum, participants
                      will explore fundamental concepts of government, democracy, and civic responsibility. 🧠
                    </p>
                  </div>
                  <div className="space-y-2 animate-fadeIn">
                    <h3
                      className="text-2xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                      Key Topics 📚
                    </h3>
                    <ul className="space-y-1 text-muted-foreground">
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Understanding the structure and function of government 🏛️
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Exploring the rights and responsibilities of citizens 🗳️
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Developing critical thinking and problem-solving skills 🧠
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Engaging in civic participation and community involvement 🤝
                      </li>
                    </ul>
                  </div>
                  <div className="space-y-2 animate-fadeIn">
                    <h3
                      className="text-2xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                      Learning Outcomes 🎯
                    </h3>
                    <ul className="space-y-1 text-muted-foreground">
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Understand the principles of democracy and the role of government 🇺🇸
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Develop critical thinking and problem-solving skills to address civic issues 🧠
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Engage in civic participation and community involvement 🤝
                      </li>
                      <li>
                        <CircleCheckIcon className="mr-2 inline h-5 w-5 text-primary animate-pulse" />
                        Become an informed and active citizen 🗳️
                      </li>
                    </ul>
                  </div>
                  <div className="flex justify-center animate-bounceIn">

                  </div>
                </div>
              </TabsContent>
              <TabsContent value="modules">
                <div />
              </TabsContent>
              <TabsContent value="videos">
                <div />
              </TabsContent>
            </Tabs>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm text-muted-foreground animate-fadeIn">
            &copy; 2024 Civic Education. All rights reserved. 🌐
          </p>
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 animate-bounceIn"
            prefetch={false}>
            Community 🤝
          </Link>
        </div>
      </footer>
    </div>)
  );
}

function CircleCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
