/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4LNUGM7cR9H
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"

export function Engage() {
  return (
    (<div className="flex min-h-screen w-full flex-col bg-background">
      <header
        className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Sheet>
          <SheetTrigger asChild>
            <Button size="icon" variant="outline" className="sm:hidden">
              <div className="h-5 w-5" />
              <span className="sr-only">Toggle Menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="sm:max-w-xs">
            <nav className="grid gap-6 text-lg font-medium">
              <Link
                href="#"
                className="group flex h-10 w-10 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:text-base"
                prefetch={false}>
                <MountainIcon className="h-5 w-5 transition-all group-hover:scale-110" />
                <span className="sr-only">Kenyan Dashboard</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-4 px-2.5 text-foreground"
                prefetch={false}>
                <FlagIcon className="h-5 w-5" />
                Public Forums
              </Link>
              <Link
                href="#"
                className="flex items-center gap-4 px-2.5 text-foreground"
                prefetch={false}>
                <VideoIcon className="h-5 w-5" />
                Online Hearings
              </Link>
              <Link
                href="#"
                className="flex items-center gap-4 px-2.5 text-foreground"
                prefetch={false}>
                <FileIcon className="h-5 w-5" />
                Written Submissions
              </Link>
              <Link
                href="#"
                className="flex items-center gap-4 px-2.5 text-foreground"
                prefetch={false}>
                <VoteIcon className="h-5 w-5" />
                Surveys and Polls
              </Link>
            </nav>
          </SheetContent>
        </Sheet>
        <Tabs defaultValue="forums">
          <TabsList className="hidden sm:flex">
            <TabsTrigger value="forums">Public Forums</TabsTrigger>
            <TabsTrigger value="hearings">Online Hearings</TabsTrigger>
            <TabsTrigger value="submissions">Written Submissions</TabsTrigger>
            <TabsTrigger value="surveys">Surveys and Polls</TabsTrigger>
          </TabsList>
        </Tabs>
        <div className="ml-auto flex items-center gap-2">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
                <img
                  src="/placeholder.svg"
                  width={36}
                  height={36}
                  alt="Avatar"
                  className="overflow-hidden rounded-full"
                  style={{ aspectRatio: "36/36", objectFit: "cover" }} />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1">
        <Tabs>
          <TabsContent value="forums">
            <div className="grid gap-6 p-4 sm:p-6 md:gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Public Forums</CardTitle>
                  <CardDescription>Engage in discussions about important topics and proposals.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Proposed Infrastructure Bill</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-06-01">June 1, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Discuss the details and potential impact of the proposed infrastructure bill.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <WebcamIcon className="h-4 w-4" />
                          <span>24</span>
                        </div>
                      </div>
                    </div>
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">New Education Policy</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-05-15">May 15, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Discuss the proposed changes to the national education policy.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <WebcamIcon className="h-4 w-4" />
                          <span>42</span>
                        </div>
                      </div>
                    </div>
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Environmental Protection Act</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-04-20">April 20, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Discuss the proposed changes to the Environmental Protection Act.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsUpIcon className="h-5 w-5" />
                          <span className="sr-only">Upvote</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <ThumbsDownIcon className="h-5 w-5" />
                          <span className="sr-only">Downvote</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <WebcamIcon className="h-4 w-4" />
                          <span>18</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="hearings">
            <div className="grid gap-6 p-4 sm:p-6 md:gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Online Hearings</CardTitle>
                  <CardDescription>Participate in live public hearings and town hall meetings.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Town Hall Meeting: Infrastructure Bill</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-06-15">June 15, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Join the live town hall meeting to discuss the proposed infrastructure bill.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <VideoIcon className="h-5 w-5" />
                          <span className="sr-only">Join</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <WebcamIcon className="h-5 w-5" />
                          <span className="sr-only">Chat</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <UsersIcon className="h-4 w-4" />
                          <span>120</span>
                        </div>
                      </div>
                    </div>
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Public Hearing: Education Policy</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-05-30">May 30, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Attend the live public hearing to provide feedback on the proposed education policy.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <VideoIcon className="h-5 w-5" />
                          <span className="sr-only">Join</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <WebcamIcon className="h-5 w-5" />
                          <span className="sr-only">Chat</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <UsersIcon className="h-4 w-4" />
                          <span>85</span>
                        </div>
                      </div>
                    </div>
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Focus Group: Environmental Protection Act</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-04-25">April 25, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">
                        Join the focus group discussion on the proposed changes to the Environmental Protection Act.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <VideoIcon className="h-5 w-5" />
                          <span className="sr-only">Join</span>
                        </Button>
                        <Button variant="ghost" size="icon" className="rounded-full">
                          <WebcamIcon className="h-5 w-5" />
                          <span className="sr-only">Chat</span>
                        </Button>
                        <div className="ml-auto flex items-center gap-1 text-sm text-muted-foreground">
                          <UsersIcon className="h-4 w-4" />
                          <span>42</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="submissions">
            <div className="grid gap-6 p-4 sm:p-6 md:gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Written Submissions</CardTitle>
                  <CardDescription>Submit your views and feedback on specific issues.</CardDescription>
                </CardHeader>
                <CardContent>
                  <form className="grid gap-4">
                    <div className="grid gap-2">
                      <Label htmlFor="subject">Subject</Label>
                      <Input id="subject" placeholder="Enter the subject of your submission" />
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="input">Your Input</Label>
                      <Textarea
                        id="input"
                        placeholder="Enter your feedback or comments"
                        className="min-h-[150px]" />
                    </div>
                    <div className="grid gap-2">
                      <Label>
                        <Checkbox /> Submit anonymously
                      </Label>
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="attachment">Attachment</Label>
                      <Input id="attachment" type="file" />
                    </div>
                    <Button type="submit">Submit</Button>
                  </form>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="surveys">
            <div className="grid gap-6 p-4 sm:p-6 md:gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Surveys and Polls</CardTitle>
                  <CardDescription>Provide feedback through interactive surveys and polls.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-2 rounded-lg bg-muted p-4">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">Infrastructure Bill Feedback</div>
                        <div className="text-xs text-muted-foreground">
                          <time dateTime="2023-06-01">June 1, 2023</time>
                        </div>
                      </div>
                      <div className="text-muted-foreground">Share your thoughts</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </main>
    </div>)
  );
}

function FileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function ThumbsDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 14V2" />
      <path
        d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>)
  );
}


function ThumbsUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 10v12" />
      <path
        d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}


function VideoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>)
  );
}


function VoteIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 12 2 2 4-4" />
      <path d="M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z" />
      <path d="M22 19H2" />
    </svg>)
  );
}


function WebcamIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>)
  );
}
