/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mlxJqmNhNXr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Input } from "@/components/ui/input"

export function InclusivityAccessibility() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link
            href="#"
            className="flex items-center gap-2 text-lg font-bold"
            prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span>Inclusive Kenya</span>
          </Link>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full">
                <GlobeIcon className="h-5 w-5" />
                <span className="sr-only">Language</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Select Language</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>English</DropdownMenuItem>
              <DropdownMenuItem>Kiswahili</DropdownMenuItem>
              <DropdownMenuItem>Kikuyu</DropdownMenuItem>
              <DropdownMenuItem>Luo</DropdownMenuItem>
              <DropdownMenuItem>Kamba</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 container mx-auto py-8 px-6">
        <Tabs defaultValue="accessibility">
          <TabsList>
            <TabsTrigger value="accessibility">Accessibility</TabsTrigger>
            <TabsTrigger value="offline">Offline Access</TabsTrigger>
            <TabsTrigger value="multilingual">Multilingual</TabsTrigger>
          </TabsList>
          <TabsContent value="accessibility">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Text-to-Speech</CardTitle>
                  <CardDescription>Enable text-to-speech for users with visual impairments.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="text-to-speech" defaultChecked />
                    <label htmlFor="text-to-speech" className="text-sm font-medium">
                      Enable Text-to-Speech
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="voice-selection">Voice Selection</Label>
                    <Select id="voice-selection">
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select Voice" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="en-US-JennyVoice">English (US) - Jenny</SelectItem>
                        <SelectItem value="sw-KE-AzizaVoice">Kiswahili (Kenya) - Aziza</SelectItem>
                        <SelectItem value="lu-KE-OkelloVoice">Luo (Kenya) - Okello</SelectItem>
                        <SelectItem value="ki-KE-WanjiruVoice">Kikuyu (Kenya) - Wanjiru</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Font Size Adjustment</CardTitle>
                  <CardDescription>Allow users to adjust the font size to their preference.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="font-size-adjustment" defaultChecked />
                    <label htmlFor="font-size-adjustment" className="text-sm font-medium">
                      Enable Font Size Adjustment
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="font-size">Font Size</Label>
                    <Slider
                      id="font-size"
                      min={12}
                      max={24}
                      defaultValue={[16]}
                      step={2}
                      aria-label="Font Size" />
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>High Contrast Mode</CardTitle>
                  <CardDescription>Provide a high-contrast mode for users with visual impairments.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="high-contrast" />
                    <label htmlFor="high-contrast" className="text-sm font-medium">
                      Enable High Contrast Mode
                    </label>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="offline">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Document Downloads</CardTitle>
                  <CardDescription>Allow users to download important documents for offline access.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="document-downloads" defaultChecked />
                    <label htmlFor="document-downloads" className="text-sm font-medium">
                      Enable Document Downloads
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="document-list">Available Documents</Label>
                    <Select id="document-list">
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select Document" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="policy-guide">Policy Guide</SelectItem>
                        <SelectItem value="application-form">Application Form</SelectItem>
                        <SelectItem value="service-catalog">Service Catalog</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>SMS Feedback</CardTitle>
                  <CardDescription>Allow users to submit feedback or views via SMS.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="sms-feedback" defaultChecked />
                    <label htmlFor="sms-feedback" className="text-sm font-medium">
                      Enable SMS Feedback
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="sms-number">SMS Number</Label>
                    <Input id="sms-number" type="tel" placeholder="+254 123 456 789" />
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>USSD Access</CardTitle>
                  <CardDescription>Provide USSD codes for users to access services without internet.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="ussd-access" defaultChecked />
                    <label htmlFor="ussd-access" className="text-sm font-medium">
                      Enable USSD Access
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="ussd-code">USSD Code</Label>
                    <Input id="ussd-code" type="text" placeholder="*123#" />
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="multilingual">
            <div className="grid gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Language Options</CardTitle>
                  <CardDescription>Provide content in multiple languages to reach a wider audience.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="multilingual-support" defaultChecked />
                    <label htmlFor="multilingual-support" className="text-sm font-medium">
                      Enable Multilingual Support
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="language-list">Supported Languages</Label>
                    <Select id="language-list" multiple>
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select Languages" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="en">English</SelectItem>
                        <SelectItem value="sw">Kiswahili</SelectItem>
                        <SelectItem value="lu">Luo</SelectItem>
                        <SelectItem value="ki">Kikuyu</SelectItem>
                        <SelectItem value="km">Kamba</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Regional Language Content</CardTitle>
                  <CardDescription>Provide content in regional languages where necessary.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Checkbox id="regional-language-content" defaultChecked />
                    <label htmlFor="regional-language-content" className="text-sm font-medium">
                      Enable Regional Language Content
                    </label>
                  </div>
                  <div className="mt-4">
                    <Label htmlFor="regional-languages">Supported Regional Languages</Label>
                    <Select id="regional-languages" multiple>
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select Regional Languages" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="lu">Luo</SelectItem>
                        <SelectItem value="ki">Kikuyu</SelectItem>
                        <SelectItem value="km">Kamba</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </main>
      <footer className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">&copy; 2024 Inclusive Kenya. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function GlobeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
