/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZbG6PeVkSp4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"

export function InformationResources() {
  return (
    (<div className="w-full">
      <section className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
          <div className="grid gap-12">
            <div className="space-y-4 text-center">
              <h2
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl animate-bounce">
                Information and Resources 🎉
              </h2>
              <p
                className="max-w-[700px] mx-auto text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Explore our latest announcements, access important documents, and learn more about the public
                participation process. 💻
              </p>
            </div>
            <Tabs defaultValue="announcements" className="w-full">
              <TabsList className="grid w-full grid-cols-3 border-b">
                <TabsTrigger value="announcements">
                  <MegaphoneIcon className="mr-2 h-5 w-5 animate-pulse" />
                  Announcements 📢
                </TabsTrigger>
                <TabsTrigger value="documents">
                  <FileIcon className="mr-2 h-5 w-5 animate-shakeX" />
                  Documents 📄
                </TabsTrigger>
                <TabsTrigger value="education">
                  <BookIcon className="mr-2 h-5 w-5 animate-spin-slow" />
                  Education 🎓
                </TabsTrigger>
              </TabsList>
              <TabsContent value="announcements" className="py-8">
                <div className="grid gap-4">
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-pulse">
                      <CalendarIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Public Hearing on Proposed Zoning Changes 🗣️</div>
                      <div className="text-muted-foreground">
                        Join us on June 15th at 7pm to share your feedback on the proposed zoning changes for the
                        downtown area. 🗓️
                      </div>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-pulse">
                      <CalendarIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Budget Proposal Public Comment Period 💰</div>
                      <div className="text-muted-foreground">
                        The proposed city budget is now available for public review. Submit your comments by July 1st.
                        📝
                      </div>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-pulse">
                      <CalendarIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Upcoming Community Meeting 🤝</div>
                      <div className="text-muted-foreground">
                        Join us on August 20th at the community center to discuss the city's transportation plan. 🚌
                      </div>
                    </div>
                  </div>
                </div>
              </TabsContent>
              <TabsContent value="documents" className="py-8">
                <div className="grid gap-4">
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-shakeX">
                      <FileIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Proposed Zoning Code Update 🏙️</div>
                      <div className="text-muted-foreground">
                        Review the full text of the proposed zoning code update. 📚
                      </div>
                      <Button variant="link" size="sm">
                        Download 💾
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-shakeX">
                      <FileIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">City Budget Proposal 💸</div>
                      <div className="text-muted-foreground">
                        Review the proposed city budget for the upcoming fiscal year. 📋
                      </div>
                      <Button variant="link" size="sm">
                        Download 💾
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-shakeX">
                      <FileIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Transportation Plan Draft 🚗</div>
                      <div className="text-muted-foreground">
                        Review the proposed transportation plan for the city. 🛣️
                      </div>
                      <Button variant="link" size="sm">
                        Download 💾
                      </Button>
                    </div>
                  </div>
                </div>
              </TabsContent>
              <TabsContent value="education" className="py-8">
                <div className="grid gap-4">
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-spin-slow">
                      <BookIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Citizen's Guide to Public Participation 🗳️</div>
                      <div className="text-muted-foreground">
                        Learn about your rights and the process for providing input on local government decisions. 💬
                      </div>
                      <Button variant="link" size="sm">
                        Read Guide 📖
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-spin-slow">
                      <BookIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Understanding the Budget Process 💰</div>
                      <div className="text-muted-foreground">
                        Explore how the city's budget is developed and how you can provide feedback. 📊
                      </div>
                      <Button variant="link" size="sm">
                        Watch Video 🎥
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <div
                      className="bg-primary rounded-md flex items-center justify-center aspect-square w-10 md:w-12 animate-spin-slow">
                      <BookIcon className="h-5 w-5 text-primary-foreground" />
                    </div>
                    <div className="grid gap-1">
                      <div className="font-medium">Zoning 101: What You Need to Know 🏢</div>
                      <div className="text-muted-foreground">
                        Understand the basics of zoning and how it impacts your community. 🏗️
                      </div>
                      <Button variant="link" size="sm">
                        Watch Video 🎥
                      </Button>
                    </div>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        </div>
      </section>
    </div>)
  );
}

function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function FileIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>)
  );
}


function MegaphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 11 18-5v12L3 14v-3z" />
      <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6" />
    </svg>)
  );
}
