/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0jZWjK62Phb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Pagination, PaginationContent, PaginationItem } from "@/components/ui/pagination"

export function Transparency() {
  return (
    (<div className="flex min-h-screen w-full flex-col bg-muted/40">
      <header
        className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Breadcrumb className="hidden md:flex">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="#" prefetch={false}>
                  Dashboard 🏠
                </Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Submission Tracker 📋</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        <div className="relative ml-auto flex-1 md:grow-0">
          <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search submissions... 🔍"
            className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[336px]" />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
              <img
                src="/placeholder.svg"
                width={36}
                height={36}
                alt="Avatar"
                className="overflow-hidden rounded-full"
                style={{ aspectRatio: "36/36", objectFit: "cover" }} />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account 👤</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings ⚙️</DropdownMenuItem>
            <DropdownMenuItem>Support 🆘</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout 🚪</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
        <Tabs defaultValue="submission-tracker" className="w-full">
          <TabsList
            className="flex w-full items-center justify-between border-b bg-background px-4 sm:px-6">
            <div className="flex gap-6 font-medium">
              <TabsTrigger value="submission-tracker">Submission Tracker 📝</TabsTrigger>
              <TabsTrigger value="outcome-reporting">Outcome Reporting 📊</TabsTrigger>
              <TabsTrigger value="public-voting">Public Voting 🗳️</TabsTrigger>
            </div>
            <Button size="sm" className="shrink-0">
              Submit New 🆕
            </Button>
          </TabsList>
          <TabsContent value="submission-tracker" className="p-4 sm:p-6">
            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Submission Tracker 📋</CardTitle>
                  <CardDescription>Track the status of your submissions and receive notifications. 🔔</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Submission</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Submitted</TableHead>
                        <TableHead>Last Updated</TableHead>
                        <TableHead>
                          <span className="sr-only">Actions</span>
                        </TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell className="font-medium">
                          <Link href="#" className="hover:underline" prefetch={false}>
                            Proposal for new park 🏞️
                          </Link>
                        </TableCell>
                        <TableCell>
                          <Badge variant="secondary">Under Review 🔍</Badge>
                        </TableCell>
                        <TableCell>2023-04-15</TableCell>
                        <TableCell>2023-05-01</TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button aria-haspopup="true" size="icon" variant="ghost">
                                <MoveHorizontalIcon className="h-4 w-4" />
                                <span className="sr-only">Toggle menu</span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem>View Details 🔍</DropdownMenuItem>
                              <DropdownMenuItem>Withdraw 🚫</DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          <Link href="#" className="hover:underline" prefetch={false}>
                            Feedback on new zoning laws 🏢
                          </Link>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">Accepted ✅</Badge>
                        </TableCell>
                        <TableCell>2023-03-28</TableCell>
                        <TableCell>2023-04-20</TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button aria-haspopup="true" size="icon" variant="ghost">
                                <MoveHorizontalIcon className="h-4 w-4" />
                                <span className="sr-only">Toggle menu</span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem>View Details 🔍</DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell className="font-medium">
                          <Link href="#" className="hover:underline" prefetch={false}>
                            Proposal for new community center 🏫
                          </Link>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">Declined ❌</Badge>
                        </TableCell>
                        <TableCell>2023-02-10</TableCell>
                        <TableCell>2023-03-15</TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button aria-haspopup="true" size="icon" variant="ghost">
                                <MoveHorizontalIcon className="h-4 w-4" />
                                <span className="sr-only">Toggle menu</span>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem>View Details 🔍</DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
                <CardFooter>
                  <Pagination>
                    <PaginationContent>
                      <PaginationItem>
                        <Button size="icon" variant="outline" className="h-6 w-6">
                          <div className="h-3.5 w-3.5" />
                          <span className="sr-only">Previous</span>
                        </Button>
                      </PaginationItem>
                      <PaginationItem>
                        <Button size="icon" variant="outline" className="h-6 w-6">
                          <div className="h-3.5 w-3.5" />
                          <span className="sr-only">Next</span>
                        </Button>
                      </PaginationItem>
                    </PaginationContent>
                  </Pagination>
                </CardFooter>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="outcome-reporting" className="p-4 sm:p-6">
            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Outcome Reporting 📊</CardTitle>
                  <CardDescription>View feedback and decisions on your submissions. 🗣️</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <div className="font-medium">Proposal for new park 🏞️</div>
                      <div className="text-sm text-muted-foreground">Submitted: 2023-04-15 | Decided: 2023-06-01</div>
                      <div className="prose text-muted-foreground">
                        <p>
                          The proposal for a new park in the city center was approved after careful consideration of
                          public feedback. The government acknowledged the community's need for more green spaces and
                          the potential benefits the park would bring. Key factors that influenced the decision include:
                        </p>
                        <ul>
                          <li>Strong support from local residents and community groups 👥</li>
                          <li>Alignment with the city's long-term sustainability goals 🌳</li>
                          <li>Feasibility of the proposed location and design 🏗️</li>
                        </ul>
                        <p>
                          The government will work closely with the submission team to finalize the design and
                          implementation plan. Construction is expected to begin in Q3 2023. 🚧
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button size="sm" variant="outline">
                          <FileTextIcon className="h-4 w-4" />
                          <span>View Report 📄</span>
                        </Button>
                        <Button size="sm" variant="outline">
                          <VideoIcon className="h-4 w-4" />
                          <span>Watch Presentation 📽️</span>
                        </Button>
                      </div>
                    </div>
                    <div className="grid gap-2">
                      <div className="font-medium">Feedback on new zoning laws 🏢</div>
                      <div className="text-sm text-muted-foreground">Submitted: 2023-03-28 | Decided: 2023-04-20</div>
                      <div className="prose text-muted-foreground">
                        <p>
                          The government has reviewed the public feedback on the proposed changes to the city's zoning
                          laws. While there was overall support for the goals of the new laws, several concerns were
                          raised regarding the impact on small businesses and affordable housing. After careful
                          consideration, the government has decided to:
                        </p>
                        <ul>
                          <li>Modify the zoning regulations to provide more protections for small businesses 🏪</li>
                          <li>Increase the minimum affordable housing requirements for new developments 🏠</li>
                          <li>Extend the implementation timeline to allow for a smoother transition 🕰️</li>
                        </ul>
                        <p>
                          The revised zoning laws will be published in the coming weeks, and the government will
                          continue to engage with the community on their implementation. 👥
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button size="sm" variant="outline">
                          <FileTextIcon className="h-4 w-4" />
                          <span>View Report 📄</span>
                        </Button>
                      </div>
                    </div>
                    <div className="grid gap-2">
                      <div className="font-medium">Proposal for new community center 🏫</div>
                      <div className="text-sm text-muted-foreground">Submitted: 2023-02-10 | Decided: 2023-03-15</div>
                      <div className="prose text-muted-foreground">
                        <p>
                          The government has carefully reviewed the proposal for a new community center and has decided
                          not to move forward with the project at this time. While the government recognizes the
                          community's need for additional public spaces, the proposed location and design were not
                          deemed feasible due to the following factors:
                        </p>
                        <ul>
                          <li>Concerns about the impact on nearby residential areas 🏘️</li>
                          <li>Budgetary constraints and competing priorities for public funding 💰</li>
                          <li>Lack of alignment with the city's long-term development plans 🗺️</li>
                        </ul>
                        <p>
                          The government encourages the submission team to consider alternative locations or designs and
                          resubmit their proposal for future consideration. We remain committed to working with the
                          community to address their needs. 🤝
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button size="sm" variant="outline">
                          <FileTextIcon className="h-4 w-4" />
                          <span>View Report 📄</span>
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="public-voting" className="p-4 sm:p-6">
            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Public Voting 🗳️</CardTitle>
                  <CardDescription>Vote on different options or proposals for certain issues. 💬</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <div className="font-medium">New Park Design 🏞️</div>
                      <div className="text-sm text-muted-foreground">Voting open until 2023-06-15</div>
                      <div className="grid gap-4 md:grid-cols-2">
                        <div className="grid gap-2 border rounded-lg p-4">
                          <img
                            src="/placeholder.svg"
                            alt="Park Design 1"
                            width={300}
                            height={200}
                            className="rounded-lg object-cover"
                            style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                          <div className="flex items-center justify-between">
                            <div>Design 1 🌳</div>
                            <Button size="sm" variant="outline">
                              Vote 🗳️
                            </Button>
                          </div>
                        </div>
                        <div className="grid gap-2 border rounded-lg p-4">
                          <img
                            src="/placeholder.svg"
                            alt="Park Design 2"
                            width={300}
                            height={200}
                            className="rounded-lg object-cover"
                            style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                          <div className="flex items-center justify-between">
                            <div>Design 2 🌳</div>
                            <Button size="sm" variant="outline">
                              Vote 🗳️
                            </Button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </main>
    </div>)
  );
}

function FileTextIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10 9H8" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </svg>)
  );
}


function MoveHorizontalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>)
  );
}


function VideoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>)
  );
}
